### PR TITLE
Make Ubuntu prereqs installer configurable + update doc

### PR DESCRIPTION
**Pull request by DestyNova**
The Ubuntu prerequisites installer currently tries to install a lot of stuff at once which you might not want (especially Java and SBT).
This PR updates the script so you can choose which steps to do (e.g. only install the bootstrap compiler or LLVM).

* Add some missing shebangs to the Ubuntu install/build scripts so they work if your default shell is not Bash
* Add getopts argument parsing to the installer
* Add colours to make output easier to follow
* Fix outdated directory in build-compiler.md + use new option syntax
* Add some auto-generated stuff to .gitignore (__MACOSX, project, target and .metals directories)

### CODE REVIEW

**Comment by Verdagon** [comment]
This looks really good, thank you for this!

Would you mind updating https://github.com/ValeLang/Vale/blob/master/.github/workflows/ci.yml to use the new command line API, so the CI passes?

Thank you!

**Comment by DestyNova** [comment]
Hi @Verdagon -- I've updated that script but it'll need your manual approval to run. I enabled workflows on my fork but for some reason it doesn't trigger, and there's no button to manually trigger the run even after adding a `workflow_dispatch:` trigger. Bummer!

**Comment by Verdagon** [comment]
Thanks for trying that! Once I get home I'll try enabling that and I'll make a second account to test out others being able to trigger it.

**Comment by Verdagon** [comment]
There's probably a better way, but it looks like you can run CI yourself if you make a separate one-line pull request to add your name to this file: https://github.com/ValeLang/Vale/blob/master/.github/contributors

**Comment by Verdagon** [comment]
Didn't notice these actually already succeeded, excellent! Thank you so much for this!

**Pull request merged**
